apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-secret
type: Opaque
data:
  username: dXNlcl9nbHBp
  password: {{ randAlphaNum 16 | b64enc }}
  root_password: {{ randAlphaNum 16 | b64enc }}