apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-phpadmin
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-phpadmin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-phpadmin
    spec:
      containers:
      - image:  phpmyadmin:latest
        name:  {{ .Release.Name }}-phpadmin
        env:
        - name: PMA_ARBITRARY
          value: "1"
        - name: PMA_HOST
          value: mariadb-service
        ports:
        - containerPort: 80